name: Test autenticación SuperManager

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * 6'

jobs:
  Get200-AUTORIZACION:
    name: Comprobar si la autorización del token es 200
    runs-on: ubuntu-latest
    env:
      SM_TOKEN: ${{ secrets.SM_TOKEN }}
      URL_JORNADA: ${{ secrets.URL_JORNADA }}
    steps:
      - uses: actions/checkout@v3  
      
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
          r-version: 'release'
          
      - name: Install libcurl and libssl on Linux
        run: sudo apt-get -y install libcurl4-openssl-dev
        shell: bash
        
      - name: Cache CRAN packages
        uses: actions/cache@v3 
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
          
      - name: Install CRAN packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages:  httr jsonlite

      - name: Run R update script
        run: Rscript scripts/test_auth.R
        shell: bash

      - name: Commit changes in data folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add png/*.png
          git diff --cached --quiet || git commit -m "Auto-update: Test autenticación SuperManager"
        shell: bash

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}on:
