name: Test autenticación SuperManager

on: 
   workflow_dispatch:
   schedule:
     - cron: '30 17 * * 4-6' 
 

jobs:
  test-auth:
    runs-on: ubuntu-latest
    env:
      SM_TOKEN: ${{ secrets.SM_TOKEN }}
      URL_JORNADA: ${{ secrets.URL_JORNADA }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # Instala solo los paquetes mínimos y sin compilar dependencias
      - name: Install libcurl and libssl on Linux
        run: sudo apt-get -y install libcurl4-openssl-dev 
        shell: bash
        
      - name: Cache CRAN packages
        uses: actions/cache@v3 
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
          
      - name: Install CRAN packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages:  httr,  jsonlite
      - name: Ejecutar test de autenticación
        run: Rscript scripts/test_auth.R
